server:
  port: 8989
  context-path: /springboot
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522:XE
    username: hr
    password: hr
mybatis:
  type-aliases-package: com.baizhi.entity